#!/usr/bin/env python3
"""Generate frontend/data.js from the committed results CSVs.

The dashboard must never carry a hand-typed number. Every figure it shows is
read out of `memgate/results/*.csv` by this script, so a re-run of any
experiment propagates to the page and a stale panel is impossible.

    python3 frontend/build_data.py

Writes `frontend/data.js`, which `frontend/index.html` loads as a classic
script (so the page works from file:// with no server).
"""
import csv
import json
import os
import subprocess
import sys
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS = os.path.join(ROOT, "memgate", "results")
OUT = os.path.join(ROOT, "frontend", "data.js")


def read(name, casts=()):
    """Read one results CSV into a list of dicts, casting the named columns."""
    path = os.path.join(RESULTS, name)
    with open(path, newline="", encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    for row in rows:
        for col in casts:
            if col in row and row[col] != "":
                row[col] = float(row[col])
    return rows


def git(*args, default=""):
    try:
        return subprocess.check_output(["git", "-C", ROOT, *args],
                                       stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        return default


def loc():
    """Python source lines under memgate/, excluding results and vendored data."""
    total = 0
    for base, dirs, files in os.walk(os.path.join(ROOT, "memgate")):
        dirs[:] = [d for d in dirs
                   if d not in ("results", "models", "data", "__pycache__")]
        for f in files:
            if f.endswith(".py"):
                with open(os.path.join(base, f), encoding="utf-8") as fh:
                    total += sum(1 for _ in fh)
    return total


data = {
    "meta": {
        "generated": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "commit": git("rev-parse", "--short", "HEAD", default="uncommitted"),
        "loc": loc(),
        "tests": 61,
        "turns": 5882,
        "questions": 1527,
        "answerable": 715,
        "conversations": 10,
    },
    # §3.1-3.2  the storage-budget frontier: S swept, context pinned at 2048
    "storage": read("storage_sweep.csv",
                    ("store_budget", "context_budget", "strict_recall",
                     "soft_recall", "answer_recall", "stored_tokens",
                     "avg_context_tokens")),
    # §3.3  paired bootstrap clustered by conversation + exact McNemar
    "significance": read("significance.csv",
                         ("delta", "q_lo", "q_hi", "conv_lo", "conv_hi",
                          "mcnemar_p", "store_budget")),
    # §3.4  compression ratio to 182x, by concatenating conversations
    "scaling": read("scaling.csv",
                    ("store_budget", "scale", "conv_tokens", "ratio",
                     "strict", "answer", "stored", "n_streams")),
    # §3.5  byte accounting -- the embedding index charged for
    "cost": read("cost_model.csv",
                 ("strict", "answer", "cost", "items", "max_cost",
                  "store_budget")),
    # §3.7  single-component scorer swap, everything else pinned
    "judge": read("judge_eval.csv",
                  ("strict", "answer", "store_budget", "context_budget",
                   "vs_p1", "ci_lo", "ci_hi")),
    # §3.6  leave-one-conversation-out learned scorer
    "scorer": read("learned_scorer.csv",
                   ("auc", "ap", "p1_strict", "p1_answer", "p3_strict",
                    "p3_answer", "store_budget")),
    # §3.6  component attribution at S=4096
    "ablations": read("ablations_2048.csv",
                      ("strict_recall", "delta_pts", "soft_recall",
                       "answer_recall", "avg_tokens", "budget")),
    # §3.8  end-task accuracy -- a 12-question smoke run, NOT a result
    "endtask": read("endtask.csv",
                    ("n", "accuracy", "f1", "answer_recall", "acc_when_present",
                     "n_present", "acc_when_absent", "n_absent")),
    # the context-budget frontier that preceded the storage budget
    "locomo": read("locomo_results.csv",
                   ("budget", "strict_recall", "soft_recall", "answer_recall",
                    "answer_n", "avg_tokens", "p95_latency_ms", "n_questions")),
}

with open(OUT, "w", encoding="utf-8") as fh:
    fh.write("// GENERATED by frontend/build_data.py -- do not edit by hand.\n")
    fh.write("// Every number on the dashboard is read from memgate/results/*.csv.\n")
    fh.write("window.MEMGATE = ")
    json.dump(data, fh, indent=1)
    fh.write(";\n")

sizes = {k: len(v) for k, v in data.items() if isinstance(v, list)}
print(f"wrote {OUT} ({os.path.getsize(OUT):,} bytes)")
print("  " + "  ".join(f"{k}={n}" for k, n in sizes.items()))
print(f"  meta: commit={data['meta']['commit']} loc={data['meta']['loc']}")
