#!/usr/bin/env python3
"""Generate the paper's numeric tables from the committed results.

    python3 paper/make_tables.py

Writes LaTeX fragments into paper/tables/, which main.tex pulls in with
\\input{}. The prose is hand-written; every number is not. This project has
already lost one results table to a stale transcription (SESSION_RECORD §16.3)
and one headline to a leak, so a paper that retypes its own numbers is a paper
waiting to disagree with its own repository.
"""
import csv
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS = os.path.join(ROOT, "memgate", "results")
OUT = os.path.join(ROOT, "paper", "tables")


def load(name, casts=()):
    with open(os.path.join(RESULTS, name), newline="", encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    for r in rows:
        for c in casts:
            if c in r and r[c] != "":
                r[c] = float(r[c])
    return rows


STORAGE = load("storage_sweep.csv", ("store_budget", "strict_recall", "answer_recall"))
SIG = load("significance.csv", ("delta", "conv_lo", "conv_hi", "mcnemar_p"))
SCALING = load("scaling.csv", ("store_budget", "ratio", "strict", "answer"))
COST = load("cost_model.csv", ("strict", "answer", "store_budget"))
JUDGE = load("judge_eval.csv", ("strict", "answer", "vs_p1", "ci_lo", "ci_hi"))
ABL = load("ablations_2048.csv", ("strict_recall", "delta_pts", "answer_recall"))


EOL = " " + "\\" * 2   # LaTeX row terminator


def write(name, body):
    path = os.path.join(OUT, name)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("% GENERATED by paper/make_tables.py -- do not edit by hand.\n")
        fh.write(body.rstrip() + "\n")
    print(f"  {name}")


def pick(prefix, budget, field):
    for r in STORAGE:
        if r["store_budget"] == budget and r["policy"].startswith(prefix):
            return r[field] * 100
    raise KeyError((prefix, budget))


def sci(p):
    """LaTeX scientific notation for a p-value."""
    if p >= 1e-3:
        return f"{p:.2f}"
    mant, exp = f"{p:.1e}".split("e")
    return f"${mant}\\!\\times\\!10^{{{int(exp)}}}$"


# ---------------------------------------------------------------- Table II
rows = []
for S in (1024, 2048, 4096, 8192, 16384):
    rag_a, adp_a, sel_a = (pick(p, S, "answer_recall") for p in ("RAG", "P1-A", "P1-S"))
    rag_e, adp_e, sel_e = (pick(p, S, "strict_recall") for p in ("RAG", "P1-A", "P1-S"))
    rows.append(
        f"{S} & {rag_e:.1f} & {adp_e:.1f} & {sel_e:.1f} & "
        f"{rag_a:.1f} & {adp_a:.1f} & \\textbf{{{sel_a:.1f}}} & "
        "\\textbf{$%+.1f$}" % (sel_a - rag_a) + EOL)
write("storage.tex", r"""\begin{tabular}{@{}rrrrrrrr@{}}
\toprule
& \multicolumn{3}{c}{Evidence recall (\%)} & \multicolumn{3}{c}{Answer recall (\%)} & \\
\cmidrule(lr){2-4}\cmidrule(lr){5-7}
$S$ & RAG & P1-A & P1-S & RAG & P1-A & P1-S & $\Delta$ \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}""")

# --------------------------------------------------------------- Table III
name = {"P1-S select vs RAG": "P1-S vs.\\ RAG (FIFO)",
        "P1-S select vs P1-A adaptive": "P1-S vs.\\ P1-A (compress)",
        "P1-S select vs P0": "P1-S vs.\\ P0 (recency)"}
order = [("P1-S select vs RAG", "answer"), ("P1-S select vs RAG", "strict"),
         ("P1-S select vs P1-A adaptive", "answer"),
         ("P1-S select vs P1-A adaptive", "strict"),
         ("P1-S select vs P0", "answer"), ("P1-S select vs P0", "strict")]
rows = []
for comp, met in order:
    r = [x for x in SIG if x["comparison"] == comp and x["metric"] == met][0]
    ns = r["conv_lo"] <= 0 <= r["conv_hi"]
    lbl = "answer" if met == "answer" else "evidence"
    delta = "$%+.2f$" % r["delta"]
    if not ns:
        delta = "\\textbf{%s}" % delta
    ci = "$[%+.2f,\\, %+.2f]$" % (r["conv_lo"], r["conv_hi"])
    verdict = "\\textsc{n.s.}" if ns else "$\\checkmark$"
    rows.append(f"{name[comp]} & {lbl} & {delta} & {ci} & "
                f"{sci(r['mcnemar_p'])} & {verdict}" + EOL)
write("significance.tex", r"""\begin{tabular}{@{}llrcrc@{}}
\toprule
Comparison & Metric & $\Delta$ (pts) & 95\% CI (clustered) & McNemar $p$ & \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}""")

# ---------------------------------------------------------------- Table IV
full = [r for r in ABL if r["configuration"] == "full system"][0]
keys = ["- retrieval (tier 3)", "- demotion on pressure", "- scored eviction (FIFO)",
        "- informative compressor", "- consolidation merge", "- supersession"]
pretty = {"- retrieval (tier 3)": "Retrieval (Tier 3)",
          "- demotion on pressure": "Demotion on pressure",
          "- scored eviction (FIFO)": "Scored eviction ($\\rightarrow$ FIFO)",
          "- informative compressor": "Informative compressor",
          "- consolidation merge": "Consolidation merge",
          "- supersession": "Semantic supersession"}
rows = []
for k in keys:
    r = [x for x in ABL if x["configuration"] == k][0]
    de = (r["strict_recall"] - full["strict_recall"]) * 100
    da = (r["answer_recall"] - full["answer_recall"]) * 100
    mark = "\\,$\\dagger$" if k == "- demotion on pressure" else ""
    rows.append("%s%s & $%+.1f$ & $%+.1f$" % (pretty[k], mark, de, da) + EOL)
write("ablation.tex", r"""\begin{tabular}{@{}lrr@{}}
\toprule
Component removed & $\Delta$ evidence & $\Delta$ answer \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}""")

# ----------------------------------------------------------------- Table V
short = {"P0 recency (no scoring)": ("P0", "position only"),
         "P1 heuristic (hand)": ("P1", "regex + shallow NER"),
         "P2 LLM judge (Qwen-0.5B)": ("P2", "the turn, in isolation"),
         "P3 learned (LOCO, bound)": ("P3", "turn + fitted base rates")}
rows = []
for r in JUDGE:
    tag, sees = short[r["scorer"]]
    is_p1 = tag == "P1"
    ans = f"\\textbf{{{r['answer']:.1f}}}" if is_p1 else f"{r['answer']:.1f}"
    rows.append(
        f"{tag} & {sees} & {r['strict']:.1f} & {ans} & "
        + ("---" if is_p1 else "$%+.2f$" % r["vs_p1"]) + " & "
        + ("---" if is_p1 else f"$[{r['ci_lo']:+.2f},\\, {r['ci_hi']:+.2f}]$") + EOL)
write("scorers.tex", r"""\begin{tabular}{@{}llrrrc@{}}
\toprule
& What the scorer sees & Evid. & Ans. & $\Delta$ vs.\ P1 & 95\% CI \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}""")

# ---------------------------------------------------------------- Table VI
def cost_at(prefix, b, field="answer"):
    for r in COST:
        if r["store_budget"] == b and r["policy"].startswith(prefix):
            return r[field]
    raise KeyError(prefix)


rows = []
for b in sorted({int(r["store_budget"]) for r in COST}):
    vals = {p: cost_at(p, b) for p in ("P0", "RAG", "P1-A", "P1-S")}
    best = max(vals.values())
    cells = " & ".join(f"\\textbf{{{v:.1f}}}" if v == best else f"{v:.1f}"
                       for v in (vals["P0"], vals["RAG"], vals["P1-A"], vals["P1-S"]))
    rows.append(f"{b // 1024} & {cells}" + EOL)
write("cost.tex", r"""\begin{tabular}{@{}rrrrr@{}}
\toprule
Budget (KiB) & P0 & RAG & P1-A & P1-S \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}""")

# --------------------------------------------------------------- Table VII
rows = []
for rank, ratio in enumerate(sorted({r["ratio"] for r in SCALING
                                     if r["store_budget"] == 2048})):
    def at(sub):
        return [r for r in SCALING if r["store_budget"] == 2048
                and r["ratio"] == ratio and sub in r["policy"]][0]["answer"]
    rag, adp, sel = at("RAG"), at("P1-A"), at("P1-S")
    rows.append(f"{ratio:.0f}$\\times$ & {rag:.1f} & {adp:.1f} & "
                + "\\textbf{%.1f} & $%+.1f$" % (sel, sel - adp) + EOL)
write("scaling.tex", r"""\begin{tabular}{@{}rrrrr@{}}
\toprule
Ratio & RAG & P1-A & P1-S & P1-S $-$ P1-A \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}""")

print(f"\nwrote 6 table fragments to {OUT}")
